import React from 'react'
import {ArrowUpRight,Check,Lock,Play,Search,ChevronRight} from 'lucide-react'

export function Button({children,variant='primary',className='',...p}:{children:React.ReactNode;variant?:'primary'|'ghost'|'outline';className?:string}&React.ButtonHTMLAttributes<HTMLButtonElement>){const v=variant==='primary'?'bg-[#e11d2e] text-white hover:bg-[#b91523]':variant==='outline'?'border border-white/15 bg-white/[.03] text-white hover:bg-white/[.07]':'text-white/70 hover:text-white';return <button className={`inline-flex items-center justify-center gap-2 rounded-full px-5 py-3 text-sm font-semibold transition-all duration-200 ${v} ${className}`} {...p}>{children}</button>}
export function Tag({children}:{children:React.ReactNode}){return <span className="inline-flex items-center rounded-full border border-white/10 bg-white/[.04] px-3 py-1 text-[10px] font-semibold uppercase tracking-[.18em] text-white/55">{children}</span>}
export function ProgressBar({value}:{value:number}){return <div className="h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-[#e11d2e]" style={{width:`${value}%`}}/></div>}
export function CourseCard({course,compact=false}:{course:any;compact?:boolean}){return <article className={`group overflow-hidden rounded-2xl border border-white/10 bg-[#111] ${compact?'md:flex':''}`}><div className={`${compact?'md:w-72':''} relative aspect-[16/10] overflow-hidden`}><img src={course.image} className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-black via-transparent to-black/10"/><div className="absolute left-4 top-4"><Tag>{course.category}</Tag></div><div className="absolute bottom-4 left-4 flex items-center gap-2"><span className="rounded-full bg-black/60 px-2.5 py-1 text-[10px] text-white/70">{course.difficulty}</span><span className="text-xs text-white/50">{course.duration}</span></div></div><div className="flex flex-1 flex-col p-5"><div className="text-[10px] uppercase tracking-[.18em] text-white/40">{course.lessons} lessons · {course.instructor}</div><h3 className="mt-2 text-xl font-semibold tracking-tight">{course.title}</h3><p className="mt-2 line-clamp-2 text-sm leading-6 text-white/55">{course.description}</p>{course.progress!==undefined&&<div className="mt-auto pt-5"><div className="mb-2 flex justify-between text-xs text-white/45"><span>{course.progress}% complete</span><span>Continue</span></div><ProgressBar value={course.progress}/></div>}{course.progress===undefined&&<Button variant="ghost" className="mt-4 w-fit px-0">View course <ArrowUpRight size={15}/></Button>}</div></article>}
export function SearchBox(){return <div className="flex items-center gap-2 rounded-full border border-white/10 bg-white/[.03] px-4 py-2.5"><Search size={16} className="text-white/40"/><input placeholder="Search academy..." className="w-full bg-transparent text-sm outline-none placeholder:text-white/30"/></div>}
export function Stat({label,value,sub}:{label:string;value:string;sub?:string}){return <div className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><div className="text-[10px] uppercase tracking-[.18em] text-white/40">{label}</div><div className="mt-2 text-3xl font-semibold tracking-tight">{value}</div>{sub&&<div className="mt-1 text-xs text-white/35">{sub}</div>}</div>}
export function LessonItem({lesson,active=false}:{lesson:any;active?:boolean}){return <div className={`flex items-center gap-3 rounded-xl border p-3 transition ${active?'border-white/15 bg-white/[.06]':'border-transparent hover:bg-white/[.04]'}`}>{lesson.done?<span className="grid size-7 place-items-center rounded-full bg-white/10 text-[#e11d2e]"><Check size={14}/></span>:<span className="grid size-7 place-items-center rounded-full border border-white/10 text-white/30">{lesson.id}</span>}<div className="min-w-0 flex-1"><div className="truncate text-sm font-medium">{lesson.title}</div><div className="text-xs text-white/35">{lesson.duration}</div></div>{!lesson.done&&<Lock size={13} className="text-white/25"/>}</div>}
